sonar.projectKey=sunkusaiabhinav_backend-quality-pipeline
sonar.projectName=backend-quality-pipeline
sonar.organization=sunkusaiabhinav

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
